# Data

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf 

from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [2]:
df = pd.read_csv("datawide.csv")

In [5]:
df.shape

(488, 18)

In [6]:
df.describe()

                 Id      month1  ...  grppc1234auto  grppc1234cat4
count  4.880000e+02  488.000000  ...     488.000000     488.000000
mean   1.736303e+07    0.798485  ...       4.508197       2.600410
std    9.380037e+06    0.775446  ...       1.902105       1.018393
min    1.037202e+07   -1.671848  ...       1.000000       1.000000
25%    1.043913e+07    0.316797  ...       3.000000       2.000000
50%    1.048816e+07    0.840045  ...       5.000000       3.000000
75%    3.003807e+07    1.326437  ...       6.000000       3.000000
max    3.012384e+07    2.637526  ...       7.000000       4.000000

[8 rows x 18 columns]

In [7]:
df.head()

         Id    month1    month6  ...  grppc123cat4  grppc1234auto  grppc1234cat4
0  10372016  1.047786  2.499978  ...             1              4              3
1  10372497  0.862626  1.070319  ...             4              2              1
2  10375097  0.933340  0.842269  ...             3              7              4
3  10375949  1.229220  1.628732  ...             1              4              3
4  10378201  1.001034  1.169967  ...             4              2              1

[5 rows x 18 columns]

In [13]:
# Only keep the group 1 and time-series data
df1 = df.iloc[:,1:12] 
df2 = df.iloc[:,1:13]
df1

       month1    month6   month12  ...   month48   month54   month60
0    1.047786  2.499978  3.878732  ...  2.192954  2.162892  2.132830
1    0.862626  1.070319  1.391754  ...  3.586301  3.454405  3.322509
2    0.933340  0.842269  0.765287  ...  1.643106  1.886483  2.129860
3    1.229220  1.628732  2.026486  ...  2.152198  2.222652  2.293106
4    1.001034  1.169967  1.398878  ...  2.780800  2.807532  2.834264
..        ...       ...       ...  ...       ...       ...       ...
483  1.042825  1.293948  1.542081  ...  1.967988  2.178712  2.389436
484  1.201370  1.864762  2.504221  ...  1.965924  1.960868  1.955812
485 -0.323836 -0.485028 -0.604531  ...  1.729967  2.337396  2.944825
486 -0.911584 -0.917232 -0.769851  ...  3.025586  3.209363  3.393140
487 -1.338716 -0.585451  0.188167  ...  1.615889  2.035861  2.455833

[488 rows x 11 columns]

# Sequence Classification with LSTM Recurrent Neural Networks in Python with Keras

In [69]:
import numpy
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
# fix random seed for reproducibility
numpy.random.seed(42)

In [66]:
df_t = np.transpose(df2)
df_t

              0         1         2    ...       485       486       487
month1   1.047786  0.862626  0.933340  ... -0.323836 -0.911584 -1.338716
month6   2.499978  1.070319  0.842269  ... -0.485028 -0.917232 -0.585451
month12  3.878732  1.391754  0.765287  ... -0.604531 -0.769851  0.188167
month18  3.438105  2.074200  0.849816  ... -0.354396  0.148320  0.310291
month24  2.997478  2.756647  0.934344  ... -0.104260  1.066490  0.432414
month30  2.556851  3.439094  1.018873  ...  0.145875  1.984660  0.554538
month36  2.253079  3.850093  1.156351  ...  0.515109  2.658032  0.775944
month42  2.223016  3.718197  1.399728  ...  1.122538  2.841809  1.195916
month48  2.192954  3.586301  1.643106  ...  1.729967  3.025586  1.615889
month54  2.162892  3.454405  1.886483  ...  2.337396  3.209363  2.035861
month60  2.132830  3.322509  2.129860  ...  2.944825  3.393140  2.455833
group1   2.000000  1.000000  4.000000  ...  4.000000  3.000000  4.000000

[12 rows x 488 columns]

In [67]:
X = df_t.iloc[:11]
X

              0         1         2    ...       485       486       487
month1   1.047786  0.862626  0.933340  ... -0.323836 -0.911584 -1.338716
month6   2.499978  1.070319  0.842269  ... -0.485028 -0.917232 -0.585451
month12  3.878732  1.391754  0.765287  ... -0.604531 -0.769851  0.188167
month18  3.438105  2.074200  0.849816  ... -0.354396  0.148320  0.310291
month24  2.997478  2.756647  0.934344  ... -0.104260  1.066490  0.432414
month30  2.556851  3.439094  1.018873  ...  0.145875  1.984660  0.554538
month36  2.253079  3.850093  1.156351  ...  0.515109  2.658032  0.775944
month42  2.223016  3.718197  1.399728  ...  1.122538  2.841809  1.195916
month48  2.192954  3.586301  1.643106  ...  1.729967  3.025586  1.615889
month54  2.162892  3.454405  1.886483  ...  2.337396  3.209363  2.035861
month60  2.132830  3.322509  2.129860  ...  2.944825  3.393140  2.455833

[11 rows x 488 columns]

In [68]:
y = df_t.iloc[11]
y

0      2.0
1      1.0
2      4.0
3      2.0
4      1.0
      ...
483    2.0
484    2.0
485    4.0
486    3.0
487    4.0
Name: group1, Length: 488, dtype: float64

In [94]:
X_array = np.transpose(X).to_numpy()
y_array = np.transpose(y).to_numpy()

In [95]:
X_array.shape, y_array.shape

((488, 11), (488,))

In [98]:
X_reshape = X_array.reshape(488,11,1)
X_reshape[1]
y_reshape = y_array.reshape(488,1)
y_reshape[1]

array([1.])

In [119]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_reshape, y_reshape, test_size=0.1, random_state=42)

In [121]:
model = Sequential()
model.add(LSTM(100))
model.add(Dense(1, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=3)
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Epoch 1/10
147/147 [==============================] - 6s 14ms/step - loss: 0.0000e+00 - accuracy: 0.1503 - val_loss: 0.0000e+00 - val_accuracy: 0.2653
Epoch 2/10
147/147 [==============================] - 1s 10ms/step - loss: 0.0000e+00 - accuracy: 0.1503 - val_loss: 0.0000e+00 - val_accuracy: 0.2653
Epoch 3/10
147/147 [==============================] - 1s 10ms/step - loss: 0.0000e+00 - accuracy: 0.1503 - val_loss: 0.0000e+00 - val_accuracy: 0.2653
Epoch 4/10
147/147 [==============================] - 1s 10ms/step - loss: 0.0000e+00 - accuracy: 0.1503 - val_loss: 0.0000e+00 - val_accuracy: 0.2653
Epoch 5/10
147/147 [==============================] - 1s 10ms/step - loss: 0.0000e+00 - accuracy: 0.1503 - val_loss: 0.0000e+00 - val_accuracy: 0.2653
Epoch 6/10
147/147 [==============================] - 1s 10ms/step - loss: 0.0000e+00 - accuracy: 0.1503 - val_loss: 0.0000e+00 - val_accuracy: 0.2653
Epoch 7/10
147/147 [==============================] - 1s 10ms/step - loss: 0.0000e+00 - accuracy: 0.1503 - val_loss: 0.0000e+00 - val_accuracy: 0.2653
Epoch 8/10
147/147 [==============================] - 1s 10ms/step - loss: 0.0000e+00 - accuracy: 0.1503 - val_loss: 0.0000e+00 - val_accuracy: 0.2653
Epoch 9/10
147/147 [==============================] - 1s 10ms/step - loss: 0.0000e+00 - accuracy: 0.1503 - val_loss: 0.0000e+00 - val_accuracy: 0.2653
Epoch 10/10
147/147 [==============================] - 1s 10ms/step - loss: 0.0000e+00 - accuracy: 0.1503 - val_loss: 0.0000e+00 - val_accuracy: 0.2653
Accuracy: 26.53%